volumes:
  etc_wireguard:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/.vds/wg-easy-15'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - INSECURE=true
      - PORT=51821
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

  mtproto-proxy:
    image: telegrammessenger/proxy
    container_name: mtproto-proxy
    restart: unless-stopped
    ports:
      - "${PORT:-484}:443"
    volumes:
      - /home/.vds/mt-proxy-config:/data
    environment:
      - SECRET=${TG_PROXY_SECRET}

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64